### ISSUE TITLE
"Google doesn't compile chromedriver versions for Linux ARM. Sorry!"

### ISSUE THREAD

**Issue by mangoheini** [f1shl/netflix-household-update#4]
Hi @f1shl ,
thank you very much for sharing this project with us!
I followed your guide but unfortunately I wasn't able to run the script on my Pi Zero W under Raspberry Pi OS Lite 32-bit (bookworm).
Every time I get that output:

`pi@strawberry:~/netflix-household-update $ /home/pi/netflix-household-update/.venv/bin/python netflix_household_update.py
Traceback (most recent call last):
  File "/home/pi/netflix-household-update/netflix_household_update.py", line 9, in <module>
    from chromedriver_py import binary_path
  File "/home/pi/netflix-household-update/.venv/lib/python3.11/site-packages/chromedriver_py/__init__.py", line 49, in <module>
    binary_path = _get_filename()
                  ^^^^^^^^^^^^^^^
  File "/home/pi/netflix-household-update/.venv/lib/python3.11/site-packages/chromedriver_py/__init__.py", line 32, in _get_filename
    raise Exception("Google doesn't compile chromedriver versions for Linux ARM. Sorry!")
`

So I installed `chromium-chromedriver` via apt and switched `UseChromedriverPy` to `False` but same result.
I'm no programmer at all but the "line 9" part in the last call lets me think some faulty or empty chromedriver_py is still involved.

Searching the web I found several people complaining on selenium not working on arm boards but no real solution to that.
Is there any chance to get this still running on a pi?

Thanks for taking your time! :)

**Comment by f1shl** [comment]
I just merged the bugfix. It should hopefully work now.
